window.NISL_ACTIVITIES.push(
  {
    id: "story-relay",
    pathway: "learn",
    subjects: ["english"],
    focuses: ["creativity", "communication", "subject-confidence"],
    ages: ["eyfs", "y1-2", "y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "The Story Relay", ar: "سباق القصة" },
    summary: { en: "Build one story together while discovering how different minds take an idea in different directions.", ar: "ابنوا قصة واحدة معاً واكتشفوا كيف تأخذ العقول المختلفة الفكرة في اتجاهات متعددة." },
    learning: { en: "story structure, listening, imagination and language confidence", ar: "بناء القصة والاستماع والخيال والثقة اللغوية" },
    equipment: { en: "board, paper and pens", ar: "السبورة والورق والأقلام" },
    starter: { en: "The teacher gives three ingredients: a place, an object and a problem. Individually imagine what could happen next.", ar: "يعطي المعلم ثلاثة عناصر: مكاناً وشيئاً ومشكلة. تخيل بمفردك ما الذي قد يحدث بعد ذلك." },
    activity: { en: "In groups, one person begins the story. Each person adds one event, sentence, drawing or spoken idea before passing it on. You must build on what came before rather than resetting the story.", ar: "في مجموعات، يبدأ شخص القصة. يضيف كل شخص حدثاً أو جملة أو رسماً أو فكرة شفهية قبل تمريرها. يجب البناء على ما سبق لا بدء قصة جديدة." },
    challenge: { en: "Give the story a satisfying ending that connects back to something introduced near the beginning. Decide which details matter and which can be removed.", ar: "امنحوا القصة نهاية مقنعة ترتبط بشيء ظهر قرب البداية. قرروا أي التفاصيل مهمة وأيها يمكن حذفه." },
    flourish: { en: "Respectful collaboration means adding to someone else’s idea without taking it over. Where did your group do that well?", ar: "التعاون المحترم يعني البناء على فكرة شخص آخر دون الاستيلاء عليها. أين نجحت مجموعتكم في ذلك؟" },
    exit: { en: "Name one contribution from someone else that made your story better.", ar: "اذكر مساهمة واحدة من شخص آخر جعلت قصتكم أفضل." },
    extension: { en: "Retell the same plot from another character’s point of view or in a completely different genre.", ar: "أعد سرد الحبكة نفسها من وجهة نظر شخصية أخرى أو في نوع أدبي مختلف تماماً." },
    teacherLens: { en: "Notice oral language, sequencing, willingness to build on others’ ideas and who naturally edits for coherence.", ar: "لاحظ اللغة الشفهية وتسلسل الأحداث والاستعداد للبناء على أفكار الآخرين ومن يقوم طبيعياً بتحسين ترابط القصة." }
  },
  {
    id: "pattern-people",
    pathway: "learn",
    subjects: ["maths"],
    focuses: ["teamwork", "creativity", "subject-confidence"],
    ages: ["eyfs", "y1-2", "y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "Human Pattern Lab", ar: "مختبر الأنماط البشرية" },
    summary: { en: "Use people, symbols and movement to create patterns that others have to decode.", ar: "استخدم الأشخاص والرموز والحركة لإنشاء أنماط يحاول الآخرون فكها." },
    learning: { en: "pattern, prediction, rules and mathematical explanation", ar: "الأنماط والتنبؤ والقواعد والشرح الرياضي" },
    equipment: { en: "board and paper", ar: "السبورة والورق" },
    starter: { en: "Continue three simple patterns the teacher puts on the board. Say the rule, not just the next item.", ar: "أكمل ثلاثة أنماط بسيطة يضعها المعلم على السبورة. اذكر القاعدة، لا العنصر التالي فقط." },
    activity: { en: "Teams create a repeating or growing pattern using positions, claps, numbers, shapes or gestures. Another team watches and states the rule.", ar: "تنشئ الفرق نمطاً متكرراً أو متنامياً باستخدام المواقع أو التصفيق أو الأرقام أو الأشكال أو الإشارات. يشاهد فريق آخر ويحدد القاعدة." },
    challenge: { en: "Create a pattern with enough information for someone to predict the 10th item without performing every step.", ar: "أنشئ نمطاً يحتوي على معلومات كافية ليتنبأ شخص بالعنصر العاشر دون تنفيذ كل الخطوات." },
    flourish: { en: "Being Ready sometimes means spotting the rule before rushing to answer. Where did careful observation help?", ar: "الاستعداد يعني أحياناً اكتشاف القاعدة قبل التسرع في الإجابة. أين ساعدت الملاحظة الدقيقة؟" },
    exit: { en: "Write or draw one pattern rule another person could follow tomorrow.", ar: "اكتب أو ارسم قاعدة نمط يستطيع شخص آخر اتباعها غداً." },
    extension: { en: "Represent the same pattern in two different ways, for example movement and numbers, then explain the connection.", ar: "مثّل النمط نفسه بطريقتين مختلفتين، مثل الحركة والأرقام، ثم اشرح العلاقة بينهما." },
    teacherLens: { en: "Notice whether students describe the underlying rule, use examples to test it and communicate patterns precisely.", ar: "لاحظ هل يصف الطلاب القاعدة الأساسية ويستخدمون أمثلة لاختبارها ويتواصلون بدقة حول الأنماط." }
  },
  {
    id: "mystery-material",
    pathway: "learn",
    subjects: ["science"],
    focuses: ["communication", "subject-confidence", "creativity"],
    ages: ["eyfs", "y1-2", "y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "Mystery Material", ar: "المادة الغامضة" },
    summary: { en: "Choose a material for a strange job and defend the properties that matter.", ar: "اختر مادة لمهمة غريبة ودافع عن الخصائص التي تجعلها مناسبة." },
    learning: { en: "properties, evidence, comparison and scientific reasoning", ar: "الخصائص والأدلة والمقارنة والاستدلال العلمي" },
    equipment: { en: "board, paper and pens", ar: "السبورة والورق والأقلام" },
    starter: { en: "Name useful properties materials can have: strong, flexible, transparent, absorbent, waterproof, conductive, light, hard, rough or others.", ar: "اذكر خصائص مفيدة للمواد: قوية، مرنة، شفافة، ماصة، مقاومة للماء، موصلة، خفيفة، صلبة، خشنة أو غيرها." },
    activity: { en: "The teacher gives a strange design job such as a desert lunchbox, a rainproof book cover or a bridge for toy animals. Teams choose or invent the best material and justify it.", ar: "يعطي المعلم مهمة تصميم غريبة مثل صندوق غداء للصحراء أو غلاف كتاب مقاوم للمطر أو جسر لحيوانات لعبة. تختار الفرق أفضل مادة أو تبتكرها وتبرر الاختيار." },
    challenge: { en: "Introduce a trade-off. Improving one property makes another worse. Which property matters most for this job and why?", ar: "أضف مفاضلة: تحسين خاصية يجعل خاصية أخرى أسوأ. أي خاصية أهم لهذه المهمة ولماذا؟" },
    flourish: { en: "Responsible scientific thinking means changing your idea when evidence is better. Did anyone in your group change their mind?", ar: "التفكير العلمي المسؤول يعني تغيير فكرتك عندما تكون الأدلة أفضل. هل غيّر أحد في مجموعتك رأيه؟" },
    exit: { en: "Complete: ‘For this job, the most important property is ___ because ___.’", ar: "أكمل: «لهذه المهمة، أهم خاصية هي ___ لأن ___.»" },
    extension: { en: "Design a fair test that could compare two candidate materials for the most important property.", ar: "صمّم اختباراً عادلاً يقارن بين مادتين مرشحتين في أهم خاصية." },
    teacherLens: { en: "Notice use of scientific vocabulary, evidence-based reasoning and whether students distinguish a material from its properties.", ar: "لاحظ استخدام المفردات العلمية والاستدلال المبني على الأدلة وقدرة الطلاب على التمييز بين المادة وخصائصها." }
  },
  {
    id: "map-my-world",
    pathway: "learn",
    subjects: ["humanities"],
    focuses: ["personalities", "creativity", "subject-confidence"],
    ages: ["eyfs", "y1-2", "y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "Map My World", ar: "خريطة عالمي" },
    summary: { en: "Create a map of places that matter, then explore how maps always involve choices.", ar: "أنشئ خريطة للأماكن المهمة ثم استكشف كيف تتضمن الخرائط دائماً اختيارات." },
    learning: { en: "place, mapping, selection and spatial communication", ar: "المكان ورسم الخرائط والاختيار والتواصل المكاني" },
    equipment: { en: "paper and pens", ar: "ورق وأقلام" },
    starter: { en: "From memory, sketch the route between two familiar places. What did you include and what did you leave out?", ar: "من الذاكرة، ارسم مساراً بين مكانين مألوفين. ماذا أضفت وماذا تركت؟" },
    activity: { en: "Create a map called ‘My World’. It can include home, school, countries, favourite places, imagined places or places that matter to your story. You decide the scale.", ar: "أنشئ خريطة بعنوان «عالمي». يمكن أن تضم المنزل والمدرسة والبلدان والأماكن المفضلة أو المتخيلة أو المهمة في قصتك. أنت تحدد المقياس." },
    challenge: { en: "Add a key and choose three symbols. Explain why those symbols communicate better than writing every label.", ar: "أضف مفتاحاً واختر ثلاثة رموز. اشرح لماذا تتواصل هذه الرموز أفضل من كتابة كل تسمية." },
    flourish: { en: "Respectful curiosity means people control what they share. Which parts of a personal map should always be optional?", ar: "الفضول المحترم يعني أن الشخص يتحكم فيما يشاركه. أي أجزاء من الخريطة الشخصية يجب أن تبقى اختيارية دائماً؟" },
    exit: { en: "Write one sentence explaining the most important choice you made as the map-maker.", ar: "اكتب جملة تشرح أهم اختيار اتخذته بصفتك صانع الخريطة." },
    extension: { en: "Redraw the map for a different audience, such as a visitor, a younger child or your future self. What changes?", ar: "أعد رسم الخريطة لجمهور مختلف مثل زائر أو طفل أصغر أو نفسك في المستقبل. ما الذي يتغير؟" },
    teacherLens: { en: "Notice spatial confidence, use of symbols, awareness of audience and willingness to explain why information is selected.", ar: "لاحظ الثقة المكانية واستخدام الرموز والوعي بالجمهور والاستعداد لشرح سبب اختيار المعلومات." }
  },
  {
    id: "human-algorithm",
    pathway: "learn",
    subjects: ["computing"],
    focuses: ["communication", "teamwork", "subject-confidence"],
    ages: ["eyfs", "y1-2", "y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "Human Algorithm", ar: "الخوارزمية البشرية" },
    summary: { en: "Discover why computers need absurdly clear instructions by becoming one.", ar: "اكتشف لماذا تحتاج الحواسيب إلى تعليمات شديدة الوضوح من خلال التحول إلى حاسوب بشري." },
    learning: { en: "algorithms, precision, debugging and communication", ar: "الخوارزميات والدقة وتصحيح الأخطاء والتواصل" },
    equipment: { en: "board, paper and pens", ar: "السبورة والورق والأقلام" },
    starter: { en: "Explain how to draw a simple shape without naming the shape. What goes wrong when instructions are vague?", ar: "اشرح كيفية رسم شكل بسيط دون ذكر اسم الشكل. ما الذي يحدث عندما تكون التعليمات غامضة؟" },
    activity: { en: "In pairs, one student writes instructions for a simple task such as drawing a symbol or moving through an imaginary grid. The other follows them exactly, not helpfully.", ar: "في أزواج، يكتب طالب تعليمات لمهمة بسيطة مثل رسم رمز أو التحرك في شبكة تخيلية. ينفذ الآخر التعليمات حرفياً لا بطريقة متعاونة." },
    challenge: { en: "Debug the instructions. Reduce ambiguity while also trying to make the algorithm shorter and easier to follow.", ar: "صحح التعليمات. قلل الغموض وحاول في الوقت نفسه جعل الخوارزمية أقصر وأسهل للاتباع." },
    flourish: { en: "Responsible communication means considering how someone else will interpret your instruction. Where did assumptions cause bugs?", ar: "التواصل المسؤول يعني التفكير في كيفية تفسير شخص آخر لتعليماتك. أين سببت الافتراضات أخطاء؟" },
    exit: { en: "Write one rule for good instructions that applies to both people and computers.", ar: "اكتب قاعدة واحدة للتعليمات الجيدة تنطبق على البشر والحواسيب معاً." },
    extension: { en: "Introduce repetition: can you replace repeated instructions with a loop or repeated command?", ar: "أدخل التكرار: هل يمكنك استبدال التعليمات المتكررة بحلقة أو أمر يتكرر؟" },
    teacherLens: { en: "Notice precision, sequencing, debugging habits and students who naturally test edge cases.", ar: "لاحظ الدقة والتسلسل وعادات تصحيح الأخطاء والطلاب الذين يختبرون الحالات غير المتوقعة بشكل طبيعي." }
  },
  {
    id: "question-ladder",
    pathway: "know",
    focuses: ["communication", "names", "confidence", "personalities"],
    ages: ["y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "The Question Ladder", ar: "سُلّم الأسئلة" },
    summary: { en: "Move from easy questions to interesting ones while practising boundaries and follow-up listening.", ar: "انتقل من الأسئلة السهلة إلى الأكثر إثارة مع التدريب على الحدود والاستماع لأسئلة المتابعة." },
    learning: { en: "conversation, questioning, names and respectful curiosity", ar: "الحوار وطرح الأسئلة والأسماء والفضول المحترم" },
    equipment: { en: "board and paper", ar: "السبورة والورق" },
    starter: { en: "Sort sample questions into three levels: easy to answer, interesting to answer, too personal for a first lesson.", ar: "صنّف أسئلة نموذجية إلى ثلاثة مستويات: سهلة الإجابة، ممتعة الإجابة، شخصية أكثر من اللازم في أول حصة." },
    activity: { en: "Pairs have two minutes each. Ask one easy question, one interesting question and one genuine follow-up based on the answer. Then switch partner.", ar: "لدى كل زوج دقيقتان. اطرح سؤالاً سهلاً وسؤالاً ممتعاً وسؤال متابعة حقيقياً يعتمد على الإجابة. ثم بدّل الشريك." },
    challenge: { en: "Write the best first-lesson question you heard or created. Test it: is it safe, open enough and likely to lead somewhere interesting?", ar: "اكتب أفضل سؤال لأول حصة سمعته أو ابتكرته. اختبره: هل هو آمن ومفتوح بما يكفي ويقود إلى حوار ممتع؟" },
    flourish: { en: "Respect includes knowing when not to push for an answer. What phrases let someone pass without awkwardness?", ar: "الاحترام يشمل معرفة متى لا نضغط للحصول على إجابة. ما العبارات التي تسمح لشخص بتجاوز السؤال دون إحراج؟" },
    exit: { en: "Write the name of one person you spoke to and one question that helped you remember them.", ar: "اكتب اسم شخص تحدثت معه وسؤالاً واحداً ساعدك على تذكره." },
    extension: { en: "Design a five-question sequence that gradually builds a useful conversation without becoming intrusive.", ar: "صمّم تسلسلاً من خمسة أسئلة يبني حواراً مفيداً تدريجياً دون أن يصبح متطفلاً." },
    teacherLens: { en: "Notice listening quality, social confidence, boundary awareness and students who ask genuine follow-up questions rather than waiting to speak.", ar: "لاحظ جودة الاستماع والثقة الاجتماعية والوعي بالحدود والطلاب الذين يطرحون أسئلة متابعة حقيقية بدلاً من انتظار دورهم للكلام." }
  },
  {
    id: "room-spectrum",
    pathway: "know",
    focuses: ["personalities", "confidence", "communication", "teamwork"],
    ages: ["y5-6", "y7-9", "y10-12"],
    title: { en: "Where Do You Stand?", ar: "أين تقف؟" },
    summary: { en: "Use a physical spectrum to reveal preferences without reducing everyone to two choices.", ar: "استخدم مقياساً حركياً لكشف التفضيلات دون حصر الجميع في خيارين فقط." },
    learning: { en: "preferences, explanation, nuance and respectful disagreement", ar: "التفضيلات والشرح والتدرج والاختلاف باحترام" },
    equipment: { en: "safe space to stand along an imaginary line", ar: "مساحة آمنة للوقوف على خط تخيلي" },
    starter: { en: "One side of the room means ‘strongly agree’, the other ‘strongly disagree’. Stand anywhere between. Try: I prefer working alone to working in a group.", ar: "أحد جانبي الغرفة يعني «أوافق بشدة» والآخر «لا أوافق بشدة». قف في أي مكان بينهما. جرّب: أفضل العمل منفرداً على العمل في مجموعة." },
    activity: { en: "Repeat with safe learning and personality statements. After each, talk to someone near you and someone much farther away. Learn their name and reasoning.", ar: "كرر باستخدام عبارات آمنة عن التعلم والشخصية. بعد كل عبارة، تحدث مع شخص قريب منك وآخر بعيد عنك. تعرّف إلى اسمه وسبب اختياره." },
    challenge: { en: "Choose one statement where your position changed after hearing someone else. What argument or example shifted you?", ar: "اختر عبارة تغير فيها موقعك بعد سماع شخص آخر. ما الحجة أو المثال الذي أثّر فيك؟" },
    flourish: { en: "A Respectful classroom does not require agreement. What does it require instead?", ar: "الصف المحترم لا يتطلب الاتفاق. ماذا يتطلب بدلاً من ذلك؟" },
    exit: { en: "Complete: ‘One thing I want teachers to know about how I participate is…’", ar: "أكمل: «شيء واحد أريد أن يعرفه المعلمون عن طريقة مشاركتي هو…»" },
    extension: { en: "Students write a spectrum statement that reveals something useful about learning without becoming personal or divisive.", ar: "يكتب الطلاب عبارة لمقياس تكشف شيئاً مفيداً عن التعلم دون أن تصبح شخصية أو مثيرة للانقسام." },
    teacherLens: { en: "Notice nuance, confidence, flexibility of thinking and whether students can disagree without turning preference into judgement.", ar: "لاحظ التدرج والثقة ومرونة التفكير وقدرة الطلاب على الاختلاف دون تحويل التفضيل إلى حكم على الآخرين." }
  },
  {
    id: "mistakes-charter",
    pathway: "culture",
    focuses: ["expectations", "confidence", "subject-confidence"],
    ages: ["y1-2", "y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "Our Mistakes Charter", ar: "ميثاقنا للأخطاء" },
    summary: { en: "Agree what should happen when someone gets an answer, decision or behaviour choice wrong.", ar: "اتفقوا على ما يجب أن يحدث عندما يخطئ شخص في إجابة أو قرار أو اختيار سلوكي." },
    learning: { en: "psychological safety, responsibility, feedback and restoration", ar: "الأمان النفسي والمسؤولية والتغذية الراجعة والإصلاح" },
    equipment: { en: "board, paper and pens", ar: "السبورة والورق والأقلام" },
    starter: { en: "Name different kinds of mistakes people make at school: learning mistakes, social mistakes and poor choices. Are they all the same?", ar: "اذكر أنواعاً مختلفة من الأخطاء في المدرسة: أخطاء التعلم، أخطاء اجتماعية، واختيارات غير مناسبة. هل كلها متشابهة؟" },
    activity: { en: "Groups create three lists: what the person who made the mistake should be able to expect, what they should take responsibility for, and what others should do next.", ar: "تنشئ المجموعات ثلاث قوائم: ما الذي يحق لمن أخطأ أن يتوقعه، وما الذي يجب أن يتحمل مسؤوليته، وما الذي يجب أن يفعله الآخرون بعد ذلك." },
    challenge: { en: "Reduce the lists to a four-line Mistakes Charter that works for both academic mistakes and everyday classroom relationships.", ar: "اختصر القوائم إلى ميثاق أخطاء من أربعة أسطر يصلح للأخطاء الأكاديمية وللعلاقات اليومية في الصف." },
    flourish: { en: "Which Flourish values make it possible to be both kind about mistakes and clear about responsibility?", ar: "أي قيم من الازدهار تجعل من الممكن أن نكون لطفاء تجاه الأخطاء وواضحين في الوقت نفسه بشأن المسؤولية؟" },
    exit: { en: "Complete privately: ‘I am more willing to take a learning risk when…’", ar: "أكمل بشكل خاص: «أكون أكثر استعداداً للمخاطرة في التعلم عندما…»" },
    extension: { en: "Create two mini-scripts: how to respond when a peer gets an answer wrong and how to respond when you have affected someone through a poor choice.", ar: "أنشئ نصين قصيرين: كيف تستجيب عندما يخطئ زميل في إجابة، وكيف تستجيب عندما تؤثر في شخص بسبب اختيار غير مناسب." },
    teacherLens: { en: "Listen for shame, fear of public error, blame and students’ expectations of adult responses. This can reveal important barriers to learning.", ar: "استمع إلى الخوف من الإحراج أو الخطأ العلني واللوم وتوقعات الطلاب لاستجابات الكبار. قد يكشف ذلك عوائق مهمة أمام التعلم." }
  }
);
