window.NISL_ACTIVITIES = [
  {
    id: "name-constellation",
    pathway: "know",
    focuses: ["names", "communication", "confidence"],
    ages: ["eyfs", "y1-2", "y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "The Name Constellation", ar: "كوكبة الأسماء" },
    summary: {
      en: "Turn a room of unfamiliar names into a visible network of connections.",
      ar: "حوّل مجموعة من الأسماء غير المألوفة إلى شبكة واضحة من الروابط."
    },
    learning: { en: "names, listening, confidence and connections", ar: "الأسماء والاستماع والثقة وبناء الروابط" },
    equipment: { en: "board, paper and pens", ar: "السبورة والورق والأقلام" },
    starter: {
      en: "Write your first name clearly. Add one small symbol beside it that represents something you enjoy, value or are curious about.",
      ar: "اكتب اسمك الأول بوضوح. أضف رمزاً صغيراً بجانبه يمثل شيئاً تستمتع به أو تقدّره أو يثير فضولك."
    },
    activity: {
      en: "In pairs, learn your partner’s name, symbol and one reason behind it. Swap partners twice. Each time, introduce the person you just met before talking about yourself.",
      ar: "في أزواج، تعرّف إلى اسم زميلك ورمزه وسبب اختياره. بدّل الشريك مرتين، وفي كل مرة قدّم الشخص الذي قابلته قبل أن تتحدث عن نفسك."
    },
    challenge: {
      en: "Build a class constellation on the board. Add names and draw lines between people who discover a shared interest, experience, language, goal or curiosity.",
      ar: "أنشئ كوكبة للصف على السبورة. أضف الأسماء وارسم خطوطاً بين الطلاب الذين يكتشفون اهتماماً أو تجربة أو لغة أو هدفاً أو فضولاً مشتركاً."
    },
    flourish: {
      en: "Which Flourish value helped us make connections today: Ready, Respectful, Responsible or Safe? Give one example you actually saw.",
      ar: "أي قيمة من قيم الازدهار ساعدتنا على بناء الروابط اليوم: مستعد، محترم، مسؤول أم آمن؟ اذكر مثالاً رأيته بالفعل."
    },
    exit: {
      en: "Write down three classmates’ names you can now remember and one thing you learned about someone else.",
      ar: "اكتب أسماء ثلاثة زملاء تستطيع تذكرهم الآن، وشيئاً واحداً تعلمته عن شخص آخر."
    },
    extension: {
      en: "Challenge the class to recreate as much of the constellation as possible from memory without looking at the board.",
      ar: "تحدَّ الصف بإعادة بناء أكبر قدر ممكن من الكوكبة من الذاكرة دون النظر إلى السبورة."
    },
    teacherLens: {
      en: "Notice who initiates conversation, who remembers names quickly, who hangs back and who helps others into the activity.",
      ar: "لاحظ من يبدأ الحوار، ومن يتذكر الأسماء سريعاً، ومن يتردد، ومن يساعد الآخرين على المشاركة."
    }
  },
  {
    id: "three-clues",
    pathway: "know",
    focuses: ["personalities", "names", "communication"],
    ages: ["y1-2", "y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "Three Clues, One Person", ar: "ثلاثة أدلة، شخص واحد" },
    summary: { en: "A low-pressure guessing game that reveals interests without forcing big personal disclosures.", ar: "لعبة تخمين بسيطة تكشف الاهتمامات دون الضغط على الطلاب لمشاركة معلومات شخصية كثيرة." },
    learning: { en: "interests, listening and class confidence", ar: "الاهتمامات والاستماع والثقة داخل الصف" },
    equipment: { en: "paper and pens", ar: "ورق وأقلام" },
    starter: { en: "Write three clues about yourself that are interesting but safe to share. Avoid your name and anything too obvious.", ar: "اكتب ثلاثة أدلة عن نفسك تكون ممتعة وآمنة للمشاركة. لا تكتب اسمك وتجنب الأمور الواضحة جداً." },
    activity: { en: "Collect and shuffle the clues. Read one set at a time. The class may ask one yes/no question before making a guess.", ar: "اجمع الأوراق واخلطها. اقرأ مجموعة واحدة في كل مرة. يمكن للصف طرح سؤال واحد إجابته نعم أو لا قبل التخمين." },
    challenge: { en: "When the person is revealed, they choose one clue to explain. The class then finds one person with something in common with them.", ar: "عند كشف صاحب الأدلة، يختار دليلاً واحداً ليشرحه. ثم يبحث الصف عن شخص لديه شيء مشترك معه." },
    flourish: { en: "What did respectful curiosity sound like during the guessing? What questions would have crossed the line?", ar: "كيف بدا الفضول المحترم أثناء التخمين؟ وما الأسئلة التي كان من الأفضل عدم طرحها؟" },
    exit: { en: "Complete: ‘One thing that surprised me about this class was…’", ar: "أكمل الجملة: «شيء واحد فاجأني في هذا الصف هو…»" },
    extension: { en: "In groups, invent a fourth clue for each member that captures something positive they noticed during the lesson.", ar: "في مجموعات، ابتكر دليلاً رابعاً لكل عضو يعبّر عن شيء إيجابي لاحظتموه خلال الحصة." },
    teacherLens: { en: "Listen for confidence, humour, boundaries and whether students show genuine curiosity about one another.", ar: "استمع إلى مستوى الثقة وروح الدعابة واحترام الحدود ومدى إظهار الطلاب فضولاً حقيقياً تجاه بعضهم البعض." }
  },
  {
    id: "identity-shield",
    pathway: "know",
    focuses: ["personalities", "creativity", "confidence"],
    ages: ["eyfs", "y1-2", "y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "Identity Shield", ar: "درع الهوية" },
    summary: { en: "Create a visual introduction that works even for students who dislike speaking first.", ar: "أنشئ مقدمة بصرية تناسب حتى الطلاب الذين لا يحبون التحدث أولاً." },
    learning: { en: "identity, creativity and self-expression", ar: "الهوية والإبداع والتعبير عن الذات" },
    equipment: { en: "paper and pens", ar: "ورق وأقلام" },
    starter: { en: "Divide a page into four sections. Use words or pictures for: something I enjoy, something I am good at, something I want to learn, something that matters to me.", ar: "قسّم الورقة إلى أربعة أقسام. استخدم كلمات أو رسوماً لـ: شيء أستمتع به، شيء أجيده، شيء أريد تعلمه، شيء مهم بالنسبة لي." },
    activity: { en: "Create your shield. You choose how much writing or drawing to use. Add a simple motto underneath if you want one.", ar: "صمّم درعك. اختر مقدار الكتابة أو الرسم الذي يناسبك. ويمكنك إضافة شعار قصير أسفل الدرع." },
    challenge: { en: "Gallery walk in pairs. Your job is to find two similarities and one interesting difference between your shields.", ar: "تجوّلوا في معرض الدروع على شكل أزواج. ابحثوا عن تشابهين واختلاف واحد مثير للاهتمام بين دروعكم." },
    flourish: { en: "Which part of your shield connects most naturally to being Ready, Respectful, Responsible or Safe?", ar: "أي جزء من درعك يرتبط أكثر بقيم: مستعد أو محترم أو مسؤول أو آمن؟" },
    exit: { en: "Circle one part of your shield you would be happy for a teacher to remember about you.", ar: "ضع دائرة حول جزء واحد من درعك يسعدك أن يتذكره معلمك عنك." },
    extension: { en: "Create a fifth section titled ‘What helps me learn well’ and add one practical suggestion.", ar: "أضف قسماً خامساً بعنوان «ما الذي يساعدني على التعلم جيداً؟» واكتب اقتراحاً عملياً واحداً." },
    teacherLens: { en: "Look for interests, strengths, aspirations and useful clues about how students prefer to participate.", ar: "ابحث عن الاهتمامات ونقاط القوة والطموحات وأي دلائل مفيدة حول الطريقة التي يفضل الطلاب المشاركة بها." }
  },
  {
    id: "silent-lineup",
    pathway: "know",
    focuses: ["teamwork", "communication", "confidence"],
    ages: ["y1-2", "y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "The Silent Line-Up", ar: "الاصطفاف الصامت" },
    summary: { en: "A quick teamwork test where communication has to happen without talking.", ar: "اختبار سريع للعمل الجماعي حيث يجب أن يحدث التواصل دون كلام." },
    learning: { en: "non-verbal communication, leadership and teamwork", ar: "التواصل غير اللفظي والقيادة والعمل الجماعي" },
    equipment: { en: "none", ar: "لا شيء" },
    starter: { en: "Without speaking, line up in birthday-month order. You may gesture, point or use fingers, but no phones and no writing.", ar: "من دون كلام، اصطفوا حسب شهر الميلاد. يمكنكم استخدام الإشارات والأصابع، لكن دون هواتف أو كتابة." },
    activity: { en: "Check the result. Then repeat with a harder category chosen by the teacher, such as alphabetical first name, travel time to school or number of languages spoken.", ar: "تحققوا من النتيجة. ثم كرروا النشاط بفئة أصعب يختارها المعلم، مثل الترتيب الأبجدي للاسم أو مدة الوصول إلى المدرسة أو عدد اللغات التي يتحدث بها الطالب." },
    challenge: { en: "In groups, decide what made the successful round work. Agree on three behaviours that improved the team.", ar: "في مجموعات، حددوا ما الذي جعل الجولة الناجحة تعمل جيداً. اتفقوا على ثلاثة سلوكيات حسّنت أداء الفريق." },
    flourish: { en: "Which mattered most here: being Respectful, Responsible or Ready? Defend your choice.", ar: "أي قيمة كانت الأهم هنا: الاحترام أم المسؤولية أم الاستعداد؟ برر اختيارك." },
    exit: { en: "Rate your team from 1–5 for listening without words. What would move the score up by one?", ar: "قيّم فريقك من 1 إلى 5 في الاستماع دون كلمات. ما الذي سيرفع التقييم درجة واحدة؟" },
    extension: { en: "Let a student leader invent the next silent sorting challenge and explain the success criteria before the class starts.", ar: "دع طالباً يقود الجولة التالية ويبتكر تحدي ترتيب صامتاً ويشرح معايير النجاح قبل البدء." },
    teacherLens: { en: "Notice natural leaders, quieter organisers, students who dominate space and students who make room for others.", ar: "لاحظ القادة الطبيعيين والمنظمين الهادئين والطلاب الذين يسيطرون على المساحة والطلاب الذين يفسحون المجال للآخرين." }
  },
  {
    id: "common-ground",
    pathway: "know",
    focuses: ["teamwork", "personalities", "communication"],
    ages: ["y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "Common Ground Challenge", ar: "تحدي القواسم المشتركة" },
    summary: { en: "Find connections that are less obvious than favourite colours and football teams.", ar: "اكتشف روابط أقل وضوحاً من الألوان المفضلة وفرق كرة القدم." },
    learning: { en: "connection, questioning and inclusion", ar: "بناء الروابط وطرح الأسئلة والشمول" },
    equipment: { en: "paper and pens", ar: "ورق وأقلام" },
    starter: { en: "In groups of four, find five things everyone in the group has in common. You cannot use school, age, uniform, nationality or being in this room.", ar: "في مجموعات من أربعة، ابحثوا عن خمسة أشياء مشتركة بين جميع أفراد المجموعة. لا يمكن استخدام المدرسة أو العمر أو الزي أو الجنسية أو وجودكم في هذه الغرفة." },
    activity: { en: "Choose your most surprising common ground and prepare a 20-second explanation of how you discovered it.", ar: "اختاروا أكثر قاسم مشترك مفاجئ وجهّزوا شرحاً مدته 20 ثانية لكيفية اكتشافه." },
    challenge: { en: "Merge with another group. Can eight people find three genuine things in common within five minutes?", ar: "انضموا إلى مجموعة أخرى. هل يستطيع ثمانية أشخاص إيجاد ثلاثة أشياء مشتركة حقيقية خلال خمس دقائق؟" },
    flourish: { en: "What does Respectful questioning look like when you are trying to learn about someone you do not know?", ar: "كيف يبدو طرح الأسئلة باحترام عندما تحاول التعرف إلى شخص لا تعرفه؟" },
    exit: { en: "Write one person’s name and one connection you discovered with them.", ar: "اكتب اسم شخص واحد ورابطاً واحداً اكتشفته معه." },
    extension: { en: "Create one question that would help a new student find common ground with this class quickly.", ar: "ابتكر سؤالاً واحداً يساعد طالباً جديداً على إيجاد قاسم مشترك مع هذا الصف بسرعة." },
    teacherLens: { en: "Watch whose ideas are heard, who asks follow-up questions and whether groups move beyond superficial similarities.", ar: "راقب أفكار من يتم الاستماع إليها، ومن يطرح أسئلة متابعة، وهل تتجاوز المجموعات أوجه التشابه السطحية." }
  },
  {
    id: "this-or-that",
    pathway: "know",
    focuses: ["confidence", "personalities", "names"],
    ages: ["eyfs", "y1-2", "y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "This, That, Then Why?", ar: "هذا أم ذاك؟ ولماذا؟" },
    summary: { en: "Fast choices get everyone moving, then the useful part begins: explaining why.", ar: "اختيارات سريعة تجعل الجميع يتحركون، ثم يبدأ الجزء الأهم: شرح السبب." },
    learning: { en: "preferences, confidence and respectful disagreement", ar: "التفضيلات والثقة والاختلاف باحترام" },
    equipment: { en: "none", ar: "لا شيء" },
    starter: { en: "Teacher gives paired choices. Move left or right: sunrise/sunset, create/compete, plan/improvise, mountains/sea, read/watch, lead/support.", ar: "يعطي المعلم اختيارات ثنائية. تحرك يميناً أو يساراً: شروق/غروب، ابتكار/منافسة، تخطيط/ارتجال، جبال/بحر، قراءة/مشاهدة، قيادة/دعم." },
    activity: { en: "After each choice, learn the name of someone near you and ask why they chose that side.", ar: "بعد كل اختيار، تعرّف إلى اسم شخص قريب منك واسأله لماذا اختار ذلك الجانب." },
    challenge: { en: "Students suggest safe this-or-that questions. Choose the ones most likely to reveal something useful about how people think or learn.", ar: "يقترح الطلاب أسئلة آمنة من نوع «هذا أم ذاك». اختاروا الأسئلة التي تكشف شيئاً مفيداً عن طريقة التفكير أو التعلم." },
    flourish: { en: "How can two people disagree and still be completely Respectful?", ar: "كيف يمكن لشخصين أن يختلفا ويظلا محترمين تماماً؟" },
    exit: { en: "Complete: ‘I changed my mind about one person because…’ or ‘I found something unexpected in common with…’", ar: "أكمل: «غيّرت فكرتي عن شخص لأن…» أو «اكتشفت شيئاً مشتركاً غير متوقع مع…»" },
    extension: { en: "Create a class continuum rather than two sides, then justify where you place yourself.", ar: "أنشئ مقياساً متدرجاً بدلاً من خيارين فقط، ثم برر مكانك على المقياس." },
    teacherLens: { en: "Notice willingness to move, explain choices, tolerate disagreement and initiate talk with unfamiliar peers.", ar: "لاحظ الاستعداد للحركة وشرح الاختيارات وتقبل الاختلاف وبدء الحوار مع زملاء غير مألوفين." }
  },
  {
    id: "mini-missions",
    pathway: "know",
    focuses: ["names", "teamwork", "communication", "confidence"],
    ages: ["eyfs", "y1-2", "y3-4", "y5-6"],
    title: { en: "Mini Missions", ar: "مهام صغيرة" },
    summary: { en: "Short, playful missions reveal how a new class works together.", ar: "مهام قصيرة ومرحة تكشف كيف يعمل الصف الجديد معاً." },
    learning: { en: "names, turn-taking and teamwork", ar: "الأسماء وتبادل الأدوار والعمل الجماعي" },
    equipment: { en: "board and paper", ar: "السبورة والورق" },
    starter: { en: "Mission 1: find someone whose name begins with a different sound from yours and learn their name.", ar: "المهمة 1: ابحث عن شخص يبدأ اسمه بصوت مختلف عن اسمك وتعرّف إلى اسمه." },
    activity: { en: "Complete three quick missions: make a group of four with four different favourite activities; arrange yourselves shortest to tallest without arguing; invent a team greeting everyone can do.", ar: "أكملوا ثلاث مهام سريعة: كوّنوا مجموعة من أربعة لكل منهم نشاط مفضل مختلف؛ رتّبوا أنفسكم من الأقصر إلى الأطول دون جدال؛ ابتكروا تحية فريق يستطيع الجميع تنفيذها." },
    challenge: { en: "Choose one mission and explain what the group did that made it work well.", ar: "اختاروا مهمة واحدة واشرحوا ما الذي فعله الفريق وجعلها تنجح." },
    flourish: { en: "Spot one example of someone being Ready, Respectful, Responsible or Safe during a mission.", ar: "ابحث عن مثال واحد لشخص كان مستعداً أو محترماً أو مسؤولاً أو آمناً أثناء إحدى المهام." },
    exit: { en: "Tell the teacher one new name you learned and one thing a good team does.", ar: "أخبر المعلم باسم جديد تعلمته وشيء واحد يفعله الفريق الجيد." },
    extension: { en: "Let groups design a safe two-minute mission for another group to attempt.", ar: "دع المجموعات تصمم مهمة آمنة مدتها دقيقتان لتجربها مجموعة أخرى." },
    teacherLens: { en: "Notice turn-taking, social confidence, willingness to include others and ability to follow a simple shared rule.", ar: "لاحظ تبادل الأدوار والثقة الاجتماعية والاستعداد لإشراك الآخرين والقدرة على اتباع قاعدة مشتركة بسيطة." }
  },
  {
    id: "learning-manual",
    pathway: "know",
    focuses: ["subject-confidence", "personalities", "expectations"],
    ages: ["y5-6", "y7-9", "y10-12"],
    title: { en: "My Learning Manual", ar: "دليل استخدامي كمتعلم" },
    summary: { en: "Students write the short instruction manual they wish teachers could read before teaching them.", ar: "يكتب الطلاب دليلاً قصيراً يتمنون لو يقرأه المعلم قبل أن يبدأ بتدريسهم." },
    learning: { en: "learning preferences, confidence and useful teacher insight", ar: "تفضيلات التعلم والثقة ومعلومات مفيدة للمعلم" },
    equipment: { en: "paper and pens", ar: "ورق وأقلام" },
    starter: { en: "Finish three sentences: I learn best when… I can find it difficult when… A teacher can help me by…", ar: "أكمل ثلاث جمل: أتعلم أفضل عندما… قد أجد صعوبة عندما… يستطيع المعلم مساعدتي من خلال…" },
    activity: { en: "Turn your answers into a one-page ‘user manual’. Include strengths, useful support, what motivates you and one thing you want to improve this year.", ar: "حوّل إجاباتك إلى «دليل استخدام» من صفحة واحدة. أضف نقاط القوة والدعم المفيد وما يحفزك وشيئاً واحداً تريد تحسينه هذا العام." },
    challenge: { en: "In pairs, compare manuals. Identify one thing teachers could do that would probably help many people in the room.", ar: "في أزواج، قارنوا الأدلة. حددوا شيئاً واحداً يمكن للمعلمين فعله وقد يساعد كثيراً من الطلاب في الغرفة." },
    flourish: { en: "Which Flourish value includes taking responsibility for knowing what helps you learn?", ar: "أي قيمة من قيم الازدهار تتضمن تحمل مسؤولية معرفة ما يساعدك على التعلم؟" },
    exit: { en: "Underline the single sentence you most want your next teacher to know.", ar: "ضع خطاً تحت الجملة الواحدة التي تريد أكثر من غيرها أن يعرفها معلمك القادم." },
    extension: { en: "Rewrite one difficulty as a practical strategy: ‘When X happens, I can…’", ar: "أعد صياغة إحدى الصعوبات كاستراتيجية عملية: «عندما يحدث كذا، أستطيع أن…»" },
    teacherLens: { en: "This is useful diagnostic information. Look for repeated themes rather than treating preferences as fixed learning styles.", ar: "هذه معلومات تشخيصية مفيدة. ابحث عن الموضوعات المتكررة ولا تتعامل مع التفضيلات على أنها أنماط تعلم ثابتة." }
  },

  {
    id: "six-word-me",
    pathway: "learn",
    subjects: ["english"],
    focuses: ["creativity", "confidence", "subject-confidence"],
    ages: ["y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "Six-Word Me", ar: "أنا في ست كلمات" },
    summary: { en: "Use extreme brevity to explore voice, word choice and identity.", ar: "استخدم الإيجاز الشديد لاستكشاف الصوت الشخصي واختيار الكلمات والهوية." },
    learning: { en: "word choice, voice and concise writing", ar: "اختيار الكلمات والصوت والكتابة الموجزة" },
    equipment: { en: "board, paper and pens", ar: "السبورة والورق والأقلام" },
    starter: { en: "Describe today in exactly six words. Count carefully. Every word has to earn its place.", ar: "صف يومك في ست كلمات بالضبط. احسب بعناية، فكل كلمة يجب أن تستحق مكانها." },
    activity: { en: "Write a six-word autobiography. It can be funny, thoughtful, ambitious or mysterious, but it must tell us something real about you.", ar: "اكتب سيرة ذاتية من ست كلمات. يمكن أن تكون مضحكة أو عميقة أو طموحة أو غامضة، لكن يجب أن تخبرنا بشيء حقيقي عنك." },
    challenge: { en: "Choose one word to change. How does replacing it alter tone or meaning? Compare two versions with a partner.", ar: "اختر كلمة واحدة لتغييرها. كيف يغيّر استبدالها النبرة أو المعنى؟ قارن نسختين مع زميل." },
    flourish: { en: "Respectful readers respond to the writing, not the person. What does good feedback sound like?", ar: "القارئ المحترم يستجيب للنص لا للشخص. كيف تبدو التغذية الراجعة الجيدة؟" },
    exit: { en: "Publish your final six words anonymously or with your name. Add one sentence explaining your most deliberate word choice.", ar: "انشر كلماتك الست النهائية باسمك أو دون اسم. أضف جملة تشرح أكثر كلمة اخترتها بعناية." },
    extension: { en: "Expand the six words into a 100-word micro-memoir without losing the original idea.", ar: "وسّع الكلمات الست إلى سيرة قصيرة من 100 كلمة دون أن تفقد الفكرة الأصلية." },
    teacherLens: { en: "Notice vocabulary confidence, willingness to revise and students who communicate more comfortably through writing than talk.", ar: "لاحظ الثقة بالمفردات والاستعداد للمراجعة والطلاب الذين يعبرون بالكتابة براحة أكبر من الكلام." }
  },
  {
    id: "numbers-about-me",
    pathway: "learn",
    subjects: ["maths"],
    focuses: ["subject-confidence", "creativity", "communication"],
    ages: ["y1-2", "y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "Numbers That Describe Me", ar: "أرقام تصفني" },
    summary: { en: "Turn personal facts into mathematical clues for classmates to decode.", ar: "حوّل حقائق شخصية إلى أدلة رياضية يفك زملاؤك رموزها." },
    learning: { en: "number sense, problem solving and mathematical communication", ar: "الحس العددي وحل المشكلات والتواصل الرياضي" },
    equipment: { en: "paper and pens", ar: "ورق وأقلام" },
    starter: { en: "Choose three numbers connected to you: for example people in your family, letters in your name, a favourite shirt number, countries lived in, pets or hobbies.", ar: "اختر ثلاثة أرقام مرتبطة بك: مثل عدد أفراد الأسرة أو حروف اسمك أو رقم رياضي مفضل أو عدد البلدان التي عشت فيها أو الحيوانات الأليفة أو الهوايات." },
    activity: { en: "Hide each number inside a calculation appropriate for you. Swap with a partner and solve before guessing what each answer might represent.", ar: "أخفِ كل رقم داخل عملية حسابية مناسبة لمستواك. تبادلها مع زميل وحلها قبل أن تخمّن ما الذي يمثله كل جواب." },
    challenge: { en: "Create one clue with more than one possible route to the answer. Compare methods rather than only answers.", ar: "أنشئ دليلاً يمكن الوصول إلى إجابته بأكثر من طريقة. قارنوا طرق الحل لا الإجابات فقط." },
    flourish: { en: "Being Responsible in maths includes showing enough working for someone else to follow. Did your clue do that?", ar: "المسؤولية في الرياضيات تشمل إظهار خطوات كافية ليتمكن شخص آخر من متابعة الحل. هل حقق دليلك ذلك؟" },
    exit: { en: "Write one calculation made by someone else that you thought was clever, clear or surprising.", ar: "اكتب عملية حسابية صممها شخص آخر ووجدتها ذكية أو واضحة أو مفاجئة." },
    extension: { en: "Create a four-clue number profile where the answers combine to reveal a final number.", ar: "أنشئ ملفاً رقمياً من أربعة أدلة تتجمع إجاباتها لتكشف رقماً نهائياً." },
    teacherLens: { en: "You will quickly see confidence with operations, notation, mental strategies and explaining mathematical thinking.", ar: "ستلاحظ سريعاً مستوى الثقة في العمليات والرموز والحساب الذهني وشرح التفكير الرياضي." }
  },
  {
    id: "alien-adaptation",
    pathway: "learn",
    subjects: ["science"],
    focuses: ["creativity", "teamwork", "subject-confidence"],
    ages: ["y1-2", "y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "Build an Alien That Survives", ar: "صمّم مخلوقاً فضائياً ينجو" },
    summary: { en: "Design a living thing for an extreme world and justify every adaptation.", ar: "صمّم كائناً حياً لعالم قاسٍ وبرر كل تكيف فيه." },
    learning: { en: "adaptation, evidence, creativity and scientific reasoning", ar: "التكيف والأدلة والإبداع والاستدلال العلمي" },
    equipment: { en: "board, paper and pens", ar: "السبورة والورق والأقلام" },
    starter: { en: "Imagine a planet that is freezing, dark, windy and has very little liquid water. What would make survival difficult?", ar: "تخيل كوكباً شديد البرودة ومظلماً وعاصفاً وفيه القليل جداً من الماء السائل. ما الذي يجعل البقاء صعباً؟" },
    activity: { en: "In teams, design an organism that could survive there. Every feature must solve a problem. Label at least four adaptations.", ar: "في فرق، صمّموا كائناً يستطيع البقاء هناك. يجب أن تحل كل صفة مشكلة معينة. ضعوا تسميات لأربعة تكيفات على الأقل." },
    challenge: { en: "Halfway through, the planet changes. The teacher adds a new condition. Adapt your organism without starting again.", ar: "في منتصف النشاط يتغير الكوكب. يضيف المعلم شرطاً جديداً. عدّلوا الكائن دون البدء من جديد." },
    flourish: { en: "Which team behaviour helped you respond when the conditions changed? Link it to one Flourish value.", ar: "أي سلوك جماعي ساعدكم عندما تغيرت الظروف؟ اربطوه بإحدى قيم الازدهار." },
    exit: { en: "Choose your organism’s single most important adaptation and explain why it matters.", ar: "اختر أهم تكيف لدى كائنك واشرح لماذا هو مهم." },
    extension: { en: "Design a predator or competitor for the same planet. How would this change your original organism over generations?", ar: "صمّم مفترساً أو منافساً على الكوكب نفسه. كيف يمكن أن يغيّر ذلك كائنك الأصلي عبر الأجيال؟" },
    teacherLens: { en: "Notice whether students can link feature to function, use evidence and revise a model when conditions change.", ar: "لاحظ قدرة الطلاب على ربط الصفة بالوظيفة واستخدام الأدلة وتعديل النموذج عند تغير الظروف." }
  },
  {
    id: "worst-city",
    pathway: "learn",
    subjects: ["humanities"],
    focuses: ["creativity", "teamwork", "subject-confidence"],
    ages: ["y5-6", "y7-9", "y10-12"],
    title: { en: "Build the Worst City in the World", ar: "ابنِ أسوأ مدينة في العالم" },
    summary: { en: "Design disaster on purpose, then reverse-engineer what makes places work.", ar: "صمّم مدينة كارثية عمداً، ثم اعكس التفكير لاكتشاف ما يجعل الأماكن ناجحة." },
    learning: { en: "place, planning, cause and effect, and argument", ar: "المكان والتخطيط والسبب والنتيجة وبناء الحجة" },
    equipment: { en: "paper and pens", ar: "ورق وأقلام" },
    starter: { en: "What could make a city difficult, unhealthy, unsafe or unpleasant to live in? Generate ideas without naming real places.", ar: "ما الذي يمكن أن يجعل المدينة صعبة أو غير صحية أو غير آمنة أو غير مريحة للعيش؟ ابتكر أفكاراً دون تسمية أماكن حقيقية." },
    activity: { en: "Teams draw the worst possible city. Consider transport, housing, services, green space, jobs, hazards, waste and where things are located.", ar: "ترسم الفرق أسوأ مدينة ممكنة. فكروا في النقل والسكن والخدمات والمساحات الخضراء والوظائف والمخاطر والنفايات ومواقع الأشياء." },
    challenge: { en: "Swap maps. The new team gets a limited budget of five changes to rescue the city. Which changes create the biggest improvement?", ar: "تبادلوا الخرائط. تحصل المجموعة الجديدة على ميزانية تسمح بخمسة تغييرات فقط لإنقاذ المدينة. أي تغييرات تحقق أكبر تحسن؟" },
    flourish: { en: "A safe community is more than rules. What features make people feel physically and socially safe?", ar: "المجتمع الآمن أكثر من مجرد قواعد. ما الخصائص التي تجعل الناس يشعرون بالأمان الجسدي والاجتماعي؟" },
    exit: { en: "Complete: ‘A successful place needs… because…’", ar: "أكمل: «المكان الناجح يحتاج إلى… لأن…»" },
    extension: { en: "Rank your five rescue changes by impact and defend the top two using social, economic and environmental reasoning.", ar: "رتّب تغييرات الإنقاذ الخمسة حسب التأثير ودافع عن أهم اثنين باستخدام أسباب اجتماعية واقتصادية وبيئية." },
    teacherLens: { en: "Look for systems thinking, spatial reasoning, prioritisation and willingness to justify choices.", ar: "ابحث عن التفكير المنظومي والاستدلال المكاني وتحديد الأولويات والاستعداد لتبرير الاختيارات." }
  },
  {
    id: "school-app",
    pathway: "learn",
    subjects: ["computing"],
    focuses: ["creativity", "teamwork", "subject-confidence"],
    ages: ["y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "Design an App This School Actually Needs", ar: "صمّم تطبيقاً تحتاجه المدرسة فعلاً" },
    summary: { en: "Start with a real problem, not a shiny solution.", ar: "ابدأ بمشكلة حقيقية، لا بحل لامع فقط." },
    learning: { en: "problem definition, users, features and digital design thinking", ar: "تعريف المشكلة والمستخدمين والخصائص والتفكير التصميمي الرقمي" },
    equipment: { en: "paper and pens", ar: "ورق وأقلام" },
    starter: { en: "List small school problems that technology might genuinely improve. Avoid problems that are really about people simply ignoring rules.", ar: "اكتب مشكلات مدرسية صغيرة يمكن للتقنية أن تحسنها فعلاً. تجنب المشكلات التي سببها الحقيقي تجاهل الناس للقواعد." },
    activity: { en: "Choose one problem. Define the user, the problem and the one thing your app must do brilliantly. Sketch three screens.", ar: "اختر مشكلة واحدة. حدّد المستخدم والمشكلة والشيء الواحد الذي يجب أن ينجزه التطبيق بإتقان. ارسم ثلاث شاشات." },
    challenge: { en: "Another team becomes the user and tests your paper prototype. They may request one change. Decide whether to accept it and explain why.", ar: "تتحول مجموعة أخرى إلى مستخدم وتجرب النموذج الورقي. يحق لها طلب تغيير واحد. قرروا قبوله أو رفضه واشرحوا السبب." },
    flourish: { en: "Responsible technology solves a problem without creating a worse one. What privacy, safety or fairness risk could your app create?", ar: "التقنية المسؤولة تحل مشكلة دون صنع مشكلة أكبر. ما مخاطر الخصوصية أو السلامة أو العدالة التي قد يسببها تطبيقكم؟" },
    exit: { en: "Pitch your app in one sentence: ‘For ___ who need ___, our app ___ without ___.’", ar: "قدّم تطبيقك في جملة واحدة: «لـ ___ الذين يحتاجون ___، يقوم تطبيقنا بـ ___ دون ___.»" },
    extension: { en: "Add a simple data model: what information would the app need, where would it come from and who should be allowed to see it?", ar: "أضف نموذج بيانات بسيطاً: ما المعلومات التي يحتاجها التطبيق؟ من أين تأتي؟ ومن المسموح له برؤيتها؟" },
    teacherLens: { en: "Notice whether students start with users and problems or jump straight to features and decoration.", ar: "لاحظ هل يبدأ الطلاب بالمستخدم والمشكلة أم يقفزون مباشرة إلى الخصائص والشكل." }
  },
  {
    id: "teach-the-teacher",
    pathway: "learn",
    subjects: ["languages"],
    focuses: ["communication", "confidence", "subject-confidence"],
    ages: ["eyfs", "y1-2", "y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "Teach the Teacher", ar: "علّم المعلم" },
    summary: { en: "Turn the languages already in the room into the lesson resource.", ar: "حوّل اللغات الموجودة بالفعل في الغرفة إلى مورد الحصة." },
    learning: { en: "pronunciation, communication, language awareness and confidence", ar: "النطق والتواصل والوعي اللغوي والثقة" },
    equipment: { en: "board and paper", ar: "السبورة والورق" },
    starter: { en: "How many languages, dialects or varieties of language are represented in this room? Build a class list without ranking them.", ar: "كم لغة أو لهجة أو تنوعاً لغوياً يوجد في هذه الغرفة؟ أنشئ قائمة صفية دون ترتيبها حسب الأفضلية." },
    activity: { en: "Pairs teach each other one useful word or phrase they know in a language or dialect. Focus on pronunciation, meaning and when it would be appropriate to use.", ar: "يعلّم كل طالب زميله كلمة أو عبارة مفيدة يعرفها بلغة أو لهجة ما. ركزوا على النطق والمعنى ومتى يكون استخدامها مناسباً." },
    challenge: { en: "Teach the teacher three new items. The class judges pronunciation kindly but accurately and helps with another attempt.", ar: "علّموا المعلم ثلاث كلمات أو عبارات جديدة. يقيّم الصف النطق بلطف ودقة ويساعده على المحاولة مرة أخرى." },
    flourish: { en: "What does Respectful correction sound like when someone is learning a new language?", ar: "كيف يبدو التصحيح المحترم عندما يتعلم شخص لغة جديدة؟" },
    exit: { en: "Write one new word or phrase you learned, what it means and who taught it to you.", ar: "اكتب كلمة أو عبارة جديدة تعلمتها ومعناها ومن علّمك إياها." },
    extension: { en: "Compare how two languages express the same idea. What changes in word order, sound or formality?", ar: "قارن كيف تعبّر لغتان عن الفكرة نفسها. ما الذي يختلف في ترتيب الكلمات أو الأصوات أو مستوى الرسمية؟" },
    teacherLens: { en: "Notice linguistic confidence, peer coaching, pronunciation awareness and how students respond to making mistakes publicly.", ar: "لاحظ الثقة اللغوية والتدريب بين الزملاء والوعي بالنطق وكيف يستجيب الطلاب للأخطاء أمام الآخرين." }
  },
  {
    id: "identity-without-face",
    pathway: "learn",
    subjects: ["art"],
    focuses: ["creativity", "personalities", "subject-confidence"],
    ages: ["eyfs", "y1-2", "y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "Identity Without a Face", ar: "هوية بلا وجه" },
    summary: { en: "Create a self-portrait without drawing your face.", ar: "أنشئ صورة ذاتية دون رسم وجهك." },
    learning: { en: "visual symbolism, composition and creative choices", ar: "الرمزية البصرية والتكوين والاختيارات الإبداعية" },
    equipment: { en: "paper and pens or pencils", ar: "ورق وأقلام أو أقلام رصاص" },
    starter: { en: "List five objects, colours, places, patterns or symbols that could say something about you without showing your face.", ar: "اكتب خمسة أشياء أو ألوان أو أماكن أو أنماط أو رموز يمكن أن تقول شيئاً عنك دون إظهار وجهك." },
    activity: { en: "Create a self-portrait using only those clues. Think about size, position, repetition and what viewers notice first.", ar: "أنشئ صورة ذاتية باستخدام تلك الدلائل فقط. فكر في الحجم والموقع والتكرار وما الذي يلاحظه المشاهد أولاً." },
    challenge: { en: "Swap work anonymously. Viewers write one interpretation and one question. The artist decides what they intended and what emerged by accident.", ar: "تبادلوا الأعمال دون أسماء. يكتب المشاهد تفسيراً واحداً وسؤالاً واحداً. يقرر الفنان ما الذي قصده وما الذي ظهر بالصدفة." },
    flourish: { en: "Respectful interpretation leaves room for the artist to disagree. How can we discuss someone’s work without claiming we know them?", ar: "التفسير المحترم يترك للفنان مساحة للاختلاف. كيف نناقش عمل شخص دون الادعاء أننا نعرفه تماماً؟" },
    exit: { en: "Choose the strongest symbol in your work and explain what makes it visually effective.", ar: "اختر أقوى رمز في عملك واشرح ما الذي يجعله فعالاً بصرياً." },
    extension: { en: "Create a second version using the same symbols but a completely different mood.", ar: "أنشئ نسخة ثانية باستخدام الرموز نفسها ولكن بمزاج بصري مختلف تماماً." },
    teacherLens: { en: "Look for risk-taking, symbolism, composition, sensitivity to interpretation and willingness to explain artistic choices.", ar: "ابحث عن الجرأة والرمزية والتكوين والحساسية تجاه التفسير والاستعداد لشرح الاختيارات الفنية." }
  },
  {
    id: "team-movement-code",
    pathway: "learn",
    subjects: ["pe"],
    focuses: ["teamwork", "communication", "confidence"],
    ages: ["eyfs", "y1-2", "y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "Team Movement Code", ar: "شفرة حركة الفريق" },
    summary: { en: "Create and decode simple movement sequences while revealing how teams organise themselves.", ar: "أنشئ وفك شفرة تسلسلات حركية بسيطة بينما تكتشف كيف تنظم الفرق نفسها." },
    learning: { en: "coordination, teamwork, memory and communication", ar: "التنسيق والعمل الجماعي والذاكرة والتواصل" },
    equipment: { en: "safe open space", ar: "مساحة آمنة ومفتوحة" },
    starter: { en: "As a class, agree four safe movements that can be performed on the spot. Give each one a number from 1–4.", ar: "كصف، اتفقوا على أربع حركات آمنة يمكن تنفيذها في المكان. أعطوا كل حركة رقماً من 1 إلى 4." },
    activity: { en: "Teams create an eight-move code using the four movements. Practise until the whole team can perform it together.", ar: "تنشئ الفرق شفرة من ثماني حركات باستخدام الحركات الأربع. تدربوا حتى يتمكن الفريق كله من تنفيذها معاً." },
    challenge: { en: "One team performs while another records the number sequence from memory, then attempts to reproduce it.", ar: "ينفذ فريق تسلسله بينما يسجل فريق آخر الأرقام من الذاكرة ثم يحاول إعادة تنفيذه." },
    flourish: { en: "Safe teamwork means adapting so everyone can take part. What did your team change to make participation possible?", ar: "العمل الجماعي الآمن يعني التكيف حتى يتمكن الجميع من المشاركة. ما الذي غيّره فريقك ليجعل المشاركة ممكنة؟" },
    exit: { en: "Name one team behaviour that improved synchronisation more than physical ability did.", ar: "اذكر سلوكاً جماعياً حسّن التزامن أكثر من القدرة البدنية نفسها." },
    extension: { en: "Add a constraint: silence, mirrored movement, change of leader or a timed transition between formations.", ar: "أضف قيداً: الصمت أو الحركة المرآتية أو تغيير القائد أو انتقالاً زمنياً بين التشكيلات." },
    teacherLens: { en: "Notice inclusion, spatial awareness, communication, leadership and whether competition remains constructive.", ar: "لاحظ الشمول والوعي بالمكان والتواصل والقيادة وما إذا بقيت المنافسة بناءة." }
  },

  {
    id: "perfect-classroom",
    pathway: "culture",
    focuses: ["expectations", "teamwork", "communication"],
    ages: ["y1-2", "y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "Design the Perfect Classroom", ar: "صمّم الصف المثالي" },
    summary: { en: "Students build expectations before seeing how closely their ideas connect with Flourish.", ar: "يبني الطلاب توقعاتهم أولاً ثم يرون مدى ارتباط أفكارهم بقيم الازدهار." },
    learning: { en: "student voice, expectations, fairness and classroom culture", ar: "صوت الطالب والتوقعات والعدالة وثقافة الصف" },
    equipment: { en: "board, paper and pens", ar: "السبورة والورق والأقلام" },
    starter: { en: "Imagine a classroom where everyone can learn, feel safe and enjoy being there. What would you notice within the first five minutes?", ar: "تخيل صفاً يستطيع فيه الجميع التعلم والشعور بالأمان والاستمتاع بوجودهم. ما الذي ستلاحظه خلال أول خمس دقائق؟" },
    activity: { en: "Teams decide: what should students expect from teachers, what should teachers expect from students, and what should classmates expect from each other?", ar: "تقرر الفرق: ماذا يجب أن يتوقع الطلاب من المعلمين؟ ماذا يجب أن يتوقع المعلمون من الطلاب؟ وماذا يجب أن يتوقع الزملاء من بعضهم؟" },
    challenge: { en: "Reduce your ideas to four behaviours only. Every behaviour must be observable, fair and useful across different lessons.", ar: "اختصروا أفكاركم إلى أربعة سلوكيات فقط. يجب أن يكون كل سلوك قابلاً للملاحظة وعادلاً ومفيداً في دروس مختلفة." },
    flourish: { en: "Reveal Ready, Respectful, Responsible and Safe. Where did your four ideas overlap? What, if anything, is missing from either list?", ar: "اكشف قيم: مستعد، محترم، مسؤول، آمن. أين تتداخل أفكاركم الأربع معها؟ وما الذي ينقص أيّاً من القائمتين إن وُجد؟" },
    exit: { en: "Student voice: ‘One thing adults should always do when responding to poor behaviour is…’", ar: "صوت الطالب: «شيء واحد يجب أن يفعله الكبار دائماً عند التعامل مع السلوك غير المناسب هو…»" },
    extension: { en: "Create one example and one non-example for each of the four Flourish values in a real classroom situation.", ar: "أنشئ مثالاً ومثالاً مضاداً لكل قيمة من قيم الازدهار الأربع في موقف صفي حقيقي." },
    teacherLens: { en: "Capture recurring student language. This is useful consultation evidence for the developing behaviour framework.", ar: "سجل العبارات المتكررة لدى الطلاب. هذه أدلة مفيدة للاستشارة حول إطار السلوك قيد التطوير." }
  },
  {
    id: "flourish-detectives",
    pathway: "culture",
    focuses: ["expectations", "communication", "teamwork"],
    ages: ["eyfs", "y1-2", "y3-4", "y5-6", "y7-9"],
    title: { en: "Flourish Detectives", ar: "محققو الازدهار" },
    summary: { en: "Spot what Ready, Respectful, Responsible and Safe actually look like in everyday situations.", ar: "اكتشف كيف تبدو قيم مستعد ومحترم ومسؤول وآمن في المواقف اليومية." },
    learning: { en: "shared language, expectations and positive recognition", ar: "اللغة المشتركة والتوقعات والتقدير الإيجابي" },
    equipment: { en: "board and paper", ar: "السبورة والورق" },
    starter: { en: "Teacher names one value. Students have 30 seconds to list everything they might see or hear if a class was showing that value well.", ar: "يسمي المعلم قيمة واحدة. لدى الطلاب 30 ثانية لذكر كل ما قد يرونه أو يسمعونه إذا كان الصف يطبق تلك القيمة جيداً." },
    activity: { en: "Give groups everyday scenarios: entering a room, group work, making a mistake, borrowing equipment, disagreeing, finishing early. Match actions to Flourish values.", ar: "أعط المجموعات مواقف يومية: دخول الصف، العمل الجماعي، ارتكاب خطأ، استعارة أدوات، الاختلاف، إنهاء العمل مبكراً. اربطوا الأفعال بقيم الازدهار." },
    challenge: { en: "Find scenarios where more than one value applies. Which value is easiest to notice? Which is easiest to misunderstand?", ar: "ابحثوا عن مواقف تنطبق عليها أكثر من قيمة. أي قيمة أسهل للملاحظة؟ وأيها أسهل لسوء الفهم؟" },
    flourish: { en: "Catch someone doing one value well during the lesson and name the exact behaviour, not just the value.", ar: "لاحظ شخصاً يطبق إحدى القيم جيداً خلال الحصة واذكر السلوك المحدد، لا اسم القيمة فقط." },
    exit: { en: "Finish: ‘Responsible does not just mean ___. It also means ___.’", ar: "أكمل: «مسؤول لا تعني فقط ___. بل تعني أيضاً ___.»" },
    extension: { en: "Create four mini-posters that define each value through observable actions rather than abstract words.", ar: "أنشئ أربعة ملصقات صغيرة تعرّف كل قيمة من خلال أفعال يمكن ملاحظتها بدلاً من كلمات مجردة." },
    teacherLens: { en: "Listen for differences in interpretation. Those are exactly the points that need clearer shared language later.", ar: "استمع إلى اختلافات التفسير. هذه بالضبط النقاط التي ستحتاج إلى لغة مشتركة أوضح لاحقاً." }
  },
  {
    id: "learning-helps-hinders",
    pathway: "culture",
    focuses: ["expectations", "subject-confidence", "communication"],
    ages: ["y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "Helps Learning / Gets in the Way", ar: "يساعد التعلم / يعيق التعلم" },
    summary: { en: "Build classroom expectations from the practical question of what actually helps people learn.", ar: "ابنِ توقعات الصف انطلاقاً من السؤال العملي: ما الذي يساعد الناس فعلاً على التعلم؟" },
    learning: { en: "metacognition, expectations and shared responsibility", ar: "ما وراء المعرفة والتوقعات والمسؤولية المشتركة" },
    equipment: { en: "board, paper and pens", ar: "السبورة والورق والأقلام" },
    starter: { en: "Draw two columns: Helps Learning / Gets in the Way. Add behaviours, routines or conditions, not names of people.", ar: "ارسم عمودين: يساعد التعلم / يعيق التعلم. أضف سلوكيات أو روتيناً أو ظروفاً، لا أسماء أشخاص." },
    activity: { en: "Groups combine lists and choose their top five in each column. For every problem, add a realistic replacement behaviour.", ar: "تجمع المجموعات قوائمها وتختار أهم خمسة في كل عمود. ولكل مشكلة، أضف سلوكاً بديلاً واقعياً." },
    challenge: { en: "Identify behaviours that can be helpful in one context and unhelpful in another, such as talking, moving, using a device or helping a friend.", ar: "حدد سلوكيات قد تكون مفيدة في سياق وضارة في سياق آخر، مثل الكلام أو الحركة أو استخدام جهاز أو مساعدة صديق." },
    flourish: { en: "Which Flourish values help us decide when a behaviour is appropriate rather than relying on a giant list of rules?", ar: "أي قيم من الازدهار تساعدنا على تحديد متى يكون السلوك مناسباً بدلاً من الاعتماد على قائمة ضخمة من القواعد؟" },
    exit: { en: "Choose one behaviour you personally control that would make this class easier to learn in.", ar: "اختر سلوكاً واحداً تتحكم فيه شخصياً وسيجعل التعلم في هذا الصف أسهل." },
    extension: { en: "Write a one-sentence principle that could replace several individual rules on your list.", ar: "اكتب مبدأً من جملة واحدة يمكن أن يحل محل عدة قواعد منفصلة في قائمتك." },
    teacherLens: { en: "Notice whether students frame success as something teachers enforce or something everyone contributes to.", ar: "لاحظ هل يرى الطلاب النجاح شيئاً يفرضه المعلم أم شيئاً يساهم فيه الجميع." }
  },
  {
    id: "fair-consequence",
    pathway: "culture",
    focuses: ["expectations", "communication", "confidence"],
    ages: ["y5-6", "y7-9", "y10-12"],
    title: { en: "What Makes a Consequence Fair?", ar: "ما الذي يجعل العاقبة عادلة؟" },
    summary: { en: "Explore fairness, certainty and restoration without presenting a finished behaviour policy.", ar: "استكشف العدالة والوضوح والإصلاح دون تقديم سياسة سلوك نهائية." },
    learning: { en: "fairness, proportionality, responsibility and student voice", ar: "العدالة والتناسب والمسؤولية وصوت الطالب" },
    equipment: { en: "board, paper and pens", ar: "السبورة والورق والأقلام" },
    starter: { en: "Which matters more in a fair consequence: being severe, being certain, being related to what happened, or helping stop it happening again? Rank them.", ar: "ما الأهم في العاقبة العادلة: أن تكون شديدة، مؤكدة، مرتبطة بما حدث، أم تساعد على عدم تكراره؟ رتّبها." },
    activity: { en: "Groups receive low-level fictional scenarios. For each, decide what a fair adult response should achieve before deciding what the response actually is.", ar: "تحصل المجموعات على مواقف خيالية بسيطة. لكل موقف، قرروا ما الذي يجب أن تحققه استجابة الكبار العادلة قبل تحديد الاستجابة نفسها." },
    challenge: { en: "Compare two approaches: punishment only versus consequence plus repair. What are the strengths and risks of each?", ar: "قارنوا بين نهجين: العقاب فقط، والعاقبة مع الإصلاح. ما نقاط القوة والمخاطر في كل منهما؟" },
    flourish: { en: "How could Ready, Respectful, Responsible and Safe guide an adult conversation after something goes wrong?", ar: "كيف يمكن لقيم مستعد ومحترم ومسؤول وآمن أن توجه حواراً بين بالغ وطالب بعد حدوث مشكلة؟" },
    exit: { en: "Student voice: write one sentence beginning ‘A consequence feels fair when…’", ar: "صوت الطالب: اكتب جملة تبدأ بـ «تبدو العاقبة عادلة عندما…»" },
    extension: { en: "Create a three-question test that staff or students could use to check whether a consequence is likely to be fair and useful.", ar: "أنشئ اختباراً من ثلاثة أسئلة يمكن للموظفين أو الطلاب استخدامه للتحقق من أن العاقبة عادلة ومفيدة." },
    teacherLens: { en: "Capture themes, especially certainty, proportionality, voice, repair and consistency. Avoid implying that draft sanctions are already live.", ar: "سجل الموضوعات المتكررة، خاصة الوضوح والتناسب والصوت والإصلاح والاتساق. تجنب الإيحاء بأن العقوبات المقترحة مطبقة بالفعل." }
  },
  {
    id: "repair-conversation",
    pathway: "culture",
    focuses: ["communication", "expectations", "confidence"],
    ages: ["y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "Repair the Moment", ar: "أصلح الموقف" },
    summary: { en: "Practise what a useful conversation sounds like after a mistake, disagreement or poor choice.", ar: "تدرّب على شكل الحوار المفيد بعد خطأ أو خلاف أو اختيار غير مناسب." },
    learning: { en: "reflection, empathy, communication and restoration", ar: "التأمل والتعاطف والتواصل والإصلاح" },
    equipment: { en: "board and paper", ar: "السبورة والورق" },
    starter: { en: "What is the difference between explaining a choice and making an excuse for it? Give one example of each.", ar: "ما الفرق بين شرح الاختيار وتقديم عذر له؟ أعط مثالاً لكل منهما." },
    activity: { en: "Use four questions with fictional scenarios: What happened? Who was affected? What needs repairing? What could happen differently next time?", ar: "استخدم أربعة أسئلة مع مواقف خيالية: ماذا حدث؟ من تأثر؟ ما الذي يحتاج إلى إصلاح؟ ما الذي يمكن أن يحدث بشكل مختلف في المرة القادمة؟" },
    challenge: { en: "Write two versions of an adult response: one that closes conversation down and one that helps a student take responsibility. Compare the language.", ar: "اكتب نسختين من استجابة بالغ: واحدة تغلق الحوار، وأخرى تساعد الطالب على تحمل المسؤولية. قارنوا اللغة." },
    flourish: { en: "Which value matters most during repair: Respectful, Responsible or Safe? Can more than one be true?", ar: "أي قيمة أهم أثناء الإصلاح: محترم أم مسؤول أم آمن؟ هل يمكن أن تكون أكثر من واحدة صحيحة؟" },
    exit: { en: "Write one sentence an adult could say that is calm, clear and leaves room for a better next choice.", ar: "اكتب جملة يمكن لبالغ قولها تكون هادئة وواضحة وتترك مساحة لاختيار أفضل في المرة القادمة." },
    extension: { en: "Create a short restorative script that sounds natural rather than robotic and test it in pairs.", ar: "أنشئ نصاً إصلاحياً قصيراً يبدو طبيعياً لا آلياً، ثم اختبره في أزواج." },
    teacherLens: { en: "Notice students’ sense of fairness and the language they believe helps adults remain firm without escalating conflict.", ar: "لاحظ مفهوم الطلاب للعدالة واللغة التي يعتقدون أنها تساعد البالغ على الثبات دون تصعيد الصراع." }
  },
  {
    id: "recognition-design",
    pathway: "culture",
    focuses: ["expectations", "creativity", "communication"],
    ages: ["y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "Design Recognition That Actually Matters", ar: "صمّم تقديراً له قيمة حقيقية" },
    summary: { en: "Ask students how positive conduct should be noticed without turning everything into prizes.", ar: "اسأل الطلاب كيف يجب ملاحظة السلوك الإيجابي دون تحويل كل شيء إلى جوائز." },
    learning: { en: "motivation, recognition, values and student voice", ar: "الدافعية والتقدير والقيم وصوت الطالب" },
    equipment: { en: "paper and pens", ar: "ورق وأقلام" },
    starter: { en: "Think of praise you have received that actually meant something. What made it feel genuine rather than automatic?", ar: "فكر في مديح تلقيته وكان له معنى حقيقي. ما الذي جعله صادقاً لا آلياً؟" },
    activity: { en: "Teams design ways to notice Ready, Respectful, Responsible and Safe. Include everyday recognition, home contact and bigger milestones.", ar: "تصمم الفرق طرقاً لملاحظة قيم مستعد ومحترم ومسؤول وآمن. أضيفوا تقديراً يومياً وتواصلاً مع المنزل ومحطات إنجاز أكبر." },
    challenge: { en: "Stress-test your ideas: Could the system become unfair, embarrassing, easy to game or focused only on already-successful students? Improve it.", ar: "اختبروا أفكاركم: هل يمكن أن يصبح النظام غير عادل أو محرجاً أو سهل التلاعب أو مركزاً فقط على الطلاب الناجحين أصلاً؟ حسّنوه." },
    flourish: { en: "Good recognition names the behaviour, not just ‘good job’. Write one specific example for each Flourish value.", ar: "التقدير الجيد يسمّي السلوك، لا يكتفي بعبارة «أحسنت». اكتب مثالاً محدداً لكل قيمة من قيم الازدهار." },
    exit: { en: "Vote privately: Which kind of recognition would motivate you most, and which would you least want?", ar: "صوّت بسرية: أي نوع من التقدير سيحفزك أكثر؟ وأي نوع لا ترغب فيه؟" },
    extension: { en: "Create a simple recognition ladder that celebrates consistency and growth, not just one-off high achievement.", ar: "أنشئ مسار تقدير بسيطاً يحتفي بالاتساق والنمو، لا بالإنجاز العالي لمرة واحدة فقط." },
    teacherLens: { en: "Excellent consultation data for the positive side of Flourish. Note differences by age and what students find authentic.", ar: "هذه بيانات ممتازة للاستشارة حول الجانب الإيجابي من الازدهار. لاحظ الاختلافات حسب العمر وما يراه الطلاب صادقاً وذا معنى." }
  },
  {
    id: "safe-space-audit",
    pathway: "culture",
    focuses: ["expectations", "teamwork", "communication"],
    ages: ["y1-2", "y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "Safe to Learn Audit", ar: "تدقيق: آمن للتعلم" },
    summary: { en: "Explore what ‘Safe’ means beyond physical safety.", ar: "استكشف معنى «آمن» بما يتجاوز السلامة الجسدية." },
    learning: { en: "physical safety, belonging, participation and learning culture", ar: "السلامة الجسدية والانتماء والمشاركة وثقافة التعلم" },
    equipment: { en: "paper and pens", ar: "ورق وأقلام" },
    starter: { en: "Complete: ‘I know a classroom is safe to learn in when…’ Generate visible and invisible signs.", ar: "أكمل: «أعرف أن الصف آمن للتعلم عندما…» ابتكر علامات ظاهرة وأخرى غير ظاهرة." },
    activity: { en: "Groups audit four areas: physical safety, safety to ask questions, safety to make mistakes, and safety to be different. What does each look and sound like?", ar: "تدقق المجموعات في أربعة مجالات: السلامة الجسدية، الأمان لطرح الأسئلة، الأمان لارتكاب الأخطاء، والأمان للاختلاف. كيف يبدو كل منها وكيف يُسمع؟" },
    challenge: { en: "Choose one area and identify what students control, what teachers control and what everyone shares responsibility for.", ar: "اختر مجالاً واحداً وحدد ما يتحكم فيه الطلاب وما يتحكم فيه المعلمون وما يتحمل الجميع مسؤوليته معاً." },
    flourish: { en: "Compare your ideas with the Flourish value Safe. Should the school definition include anything else?", ar: "قارن أفكارك بقيمة «آمن» في الازدهار. هل يجب أن يتضمن تعريف المدرسة شيئاً إضافياً؟" },
    exit: { en: "One practical thing that would make it easier for me to ask for help in class is…", ar: "شيء عملي واحد سيجعل طلب المساعدة في الصف أسهل بالنسبة لي هو…" },
    extension: { en: "Write three student-friendly indicators that could be used to check whether a classroom feels safe to learn in over time.", ar: "اكتب ثلاثة مؤشرات بلغة الطلاب يمكن استخدامها للتحقق مع الوقت مما إذا كان الصف آمناً للتعلم." },
    teacherLens: { en: "Listen carefully for barriers to asking questions, making mistakes or seeking help. These insights can be more useful than generic behaviour rules.", ar: "استمع بعناية إلى العوائق أمام طرح الأسئلة أو ارتكاب الأخطاء أو طلب المساعدة. قد تكون هذه الأفكار أكثر فائدة من قواعد السلوك العامة." }
  },
  {
    id: "classroom-constitution",
    pathway: "culture",
    focuses: ["expectations", "teamwork", "creativity"],
    ages: ["y5-6", "y7-9", "y10-12"],
    title: { en: "The Four-Line Classroom Constitution", ar: "دستور الصف في أربعة أسطر" },
    summary: { en: "Compress a mountain of rules into four principles students can actually remember.", ar: "اختصر جبلاً من القواعد إلى أربعة مبادئ يستطيع الطلاب تذكرها فعلاً." },
    learning: { en: "principles, clarity, shared ownership and concise writing", ar: "المبادئ والوضوح والملكية المشتركة والكتابة الموجزة" },
    equipment: { en: "board, paper and pens", ar: "السبورة والورق والأقلام" },
    starter: { en: "What is the problem with a classroom having 25 separate rules? What is the problem with having only ‘be good’?", ar: "ما مشكلة وجود 25 قاعدة منفصلة في الصف؟ وما مشكلة الاكتفاء بعبارة «كن جيداً»؟" },
    activity: { en: "Groups write a classroom constitution of exactly four lines. Each line must be broad enough to matter but specific enough to guide a real choice.", ar: "تكتب المجموعات دستوراً صفياً من أربعة أسطر بالضبط. يجب أن يكون كل سطر واسعاً بما يكفي ليكون مهماً ومحدداً بما يكفي لتوجيه اختيار حقيقي." },
    challenge: { en: "Test each line against tricky situations: group disagreement, unfinished work, late arrival, misuse of equipment, someone making a mistake.", ar: "اختبر كل سطر أمام مواقف صعبة: خلاف جماعي، عمل غير مكتمل، تأخر، سوء استخدام أدوات، ارتكاب شخص لخطأ." },
    flourish: { en: "Now compare your constitution with Ready, Respectful, Responsible and Safe. Which wording is clearer to students? Can the two strengthen each other?", ar: "قارن الآن دستورك بقيم مستعد ومحترم ومسؤول وآمن. أي صياغة أوضح للطلاب؟ وهل يمكن أن يقوي أحدهما الآخر؟" },
    exit: { en: "Choose the one line you think would make the biggest difference if everyone genuinely followed it.", ar: "اختر السطر الواحد الذي تعتقد أنه سيحدث أكبر فرق إذا التزم به الجميع بصدق." },
    extension: { en: "Rewrite the four lines as positive actions rather than prohibitions. Remove every ‘don’t’."
      , ar: "أعد كتابة الأسطر الأربعة كأفعال إيجابية بدلاً من المنع. احذف كل صياغة تبدأ بـ «لا»." },
    teacherLens: { en: "This reveals the values and routines students instinctively prioritise, and where their language aligns with Flourish.", ar: "يكشف هذا القيم والروتين الذي يعطيه الطلاب الأولوية بشكل طبيعي ومدى توافق لغتهم مع الازدهار." }
  },
  {
    id: "scenario-sort",
    pathway: "culture",
    focuses: ["expectations", "communication", "teamwork"],
    ages: ["y3-4", "y5-6", "y7-9", "y10-12"],
    title: { en: "Same Situation, Different Response", ar: "الموقف نفسه، استجابات مختلفة" },
    summary: { en: "Explore why context matters and why consistency does not mean every incident is identical.", ar: "استكشف لماذا يهم السياق ولماذا لا يعني الاتساق أن كل حادثة متطابقة." },
    learning: { en: "judgement, context, fairness and shared language", ar: "الحكم والسياق والعدالة واللغة المشتركة" },
    equipment: { en: "board and paper", ar: "السبورة والورق" },
    starter: { en: "Is treating everyone fairly always the same as treating everyone exactly the same? Give a non-school example.", ar: "هل تعني معاملة الجميع بعدل دائماً معاملتهم بالطريقة نفسها تماماً؟ أعط مثالاً من خارج المدرسة." },
    activity: { en: "Compare pairs of fictional situations that look similar but have different context. Decide what an adult needs to know before responding.", ar: "قارن أزواجاً من المواقف الخيالية التي تبدو متشابهة لكن سياقها مختلف. قرر ما الذي يحتاج البالغ إلى معرفته قبل الاستجابة." },
    challenge: { en: "For each pair, identify what should stay consistent: expectation, language, process, consequence, support or recording.", ar: "لكل زوج، حدد ما الذي يجب أن يبقى متسقاً: التوقع، اللغة، الإجراء، العاقبة، الدعم أم التسجيل." },
    flourish: { en: "Which Flourish value is most useful when making a fair decision with incomplete information?", ar: "أي قيمة من قيم الازدهار أكثر فائدة عند اتخاذ قرار عادل بمعلومات غير مكتملة؟" },
    exit: { en: "Complete: ‘Consistency should mean ___, not necessarily ___.’", ar: "أكمل: «يجب أن يعني الاتساق ___، وليس بالضرورة ___.»" },
    extension: { en: "Design one fictional scenario where a serious safety issue should clearly bypass an ordinary staged response.", ar: "صمّم موقفاً خيالياً واحداً تكون فيه مشكلة سلامة جسيمة سبباً واضحاً لتجاوز الاستجابة التدريجية المعتادة." },
    teacherLens: { en: "Useful for testing whether students understand the difference between predictable systems and automatic tariffs.", ar: "مفيد لاختبار فهم الطلاب للفرق بين الأنظمة المتوقعة والعقوبات الآلية." }
  }
];
